services:
  app:
    build: .
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command:
      - "/bin/bash"
      - "-c"
      - "yarn build && yarn serve"
