services:
  app:
    build: .
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - | 
        yarn build && yarn serve
